# windows release build: mingw64 g++ from MSYS2 (currently 9.1.1) on Windows Server 2012 R2
image:
  - Visual Studio 2015

clone_folder: C:\msys64\home\appveyor\dune-copasi

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  # download muparser, gmp and libtiff as static libraries
  - cd C:\msys64\usr\
  - appveyor DownloadFile "https://github.com/lkeegan/libsbml-static/releases/latest/download/libsbml-static-windows.zip"
  - 7z x libsbml-static-windows.zip -aos
  - dir
  - dir lib
  - dir include
  - cd C:\msys64\home\appveyor/usr

before_build:
  # - set DEPS_DIR=\home\appveyor\ext
  - echo CMAKE_FLAGS="-G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release  -DCMAKE_VERBOSE_MAKEFILE=1 " > C:\msys64\home\appveyor\dune.txt
  - echo CMAKE_FLAGS+=" -DDUNE_PYTHON_VIRTUALENV_SETUP=0 -DDUNE_PYTHON_ALLOW_GET_PIP=0" >> C:\msys64\home\appveyor\dune.txt
  - echo CMAKE_FLAGS+=" -DDUNE_PYTHON_VIRTUALENV_PATH=%DEPS_DIR%/dune-python-venv" >> C:\msys64\home\appveyor\dune.txt
  # - echo CMAKE_FLAGS+=" -DGMPXX_INCLUDE_DIR:PATH=%DEPS_DIR%/include -DGMPXX_LIB:FILEPATH=%DEPS_DIR%/lib/libgmpxx.a -DGMP_LIB:FILEPATH=%DEPS_DIR%/lib/libgmp.a" >> C:\msys64\home\appveyor\dune.txt
  - echo CMAKE_FLAGS+=" -DCMAKE_DISABLE_FIND_PACKAGE_QuadMath=TRUE" >> C:\msys64\home\appveyor\dune.txt
  - echo CMAKE_FLAGS+=" -DBUILD_TESTING=OFF -DDUNE_USE_ONLY_STATIC_LIBS=ON" >> C:\msys64\home\appveyor\dune.txt
  # - echo CMAKE_FLAGS+=" -DCMAKE_PREFIX_PATH=/ >> C:\msys64\home\appveyor\dune.txt
  # - echo CMAKE_FLAGS+=" -Dmuparser_INCLUDE_DIR:PATH=%DEPS_DIR%/include -Dmuparser_LIBRARY:PATH=%DEPS_DIR%/lib/libmuparser.a -DTIFF_ROOT=%DEPS_DIR%  " >> C:\msys64\home\appveyor\dune.txt
  - echo CMAKE_FLAGS+=" -DF77=true -DCMAKE_CXX_FLAGS='-Wa,-mbig-obj -static -static-libgcc -static-libstdc++' " >> C:\msys64\home\appveyor\dune.txt
  - echo MAKE_FLAGS="-j2 VERBOSE=1" >> C:\msys64\home\appveyor\dune.txt
  - type C:\msys64\home\appveyor\dune.txt
  - set DUNE_OPTIONS_FILE=dune.txt
  - set DUNECONTROL=./dune-common/bin/dunecontrol
  - bash -l C:\msys64\home\appveyor\dune-copasi\.ci\setup.sh

build_script:
  - bash -l C:\msys64\home\appveyor\dune-copasi\.ci\build.sh

test_script:
  - bash -l C:\msys64\home\appveyor\dune-copasi\.ci\system_tests.sh
  - bash -l C:\msys64\home\appveyor\dune-copasi\.ci\unit_tests.sh